### Numpy


Numpy stands for Numerical Python.

It is a popular Python library built on C programming which is used for scientific computing.

### Advantages of Numpy


- Numpy array manipulations are faster as compared to the list data structure.
- Numpy provides a wide range of universal functions for performing element-wise opperations on arrays such as addition, multiplicaton 
- NumPy provides a powerful and flexible data structure called ndarrays (N-dimensional arrays), which can represent and manipulate data in multiple dimensions.
- NumPy's broadcasting feature allows arrays with different shapes to be used in arithmetic operations, which can greatly simplify code and reduce memory usage.

### Installation of Numpy

The numpy library can be installed using the following:


**1. Command Prompt**

- Launch the command prompt
- Type the code below to install the numpy library

`pip install numpy`



**2. Anaconda Terminal**

- Launch the anaconda terminal
- Type the code below to install the numpy library

`conda install numpy`


### Using Numpy

To use the numpy library import the numpy library using:

`import numpy as np`

The **np** is the popular alias for the numpy library.

In [1]:
import numpy as np

### Numpy Arrays

A numpy array is a grid of values with the same data type and that is indexed by a tuple of non-negative integers.

Numpy arrays can havr any number of dimensions, but the most popular types are the one dimensional array(vectors) and two dimensional arrays(matrices)

#### Creating  a 1D array

In [2]:
arr_1 = np.array([1,2,3,4])

In [3]:
arr_1

array([1, 2, 3, 4])

In [4]:
#Check the dimension of the array
arr_1.ndim

1

In [5]:
#check the shape of the array
arr_1.shape

(4,)

#### Creating a 1D array from a list

In [6]:
ls_1 = [2,3,4,5]

In [7]:
arr_2 = np.array(ls_1)

In [8]:
arr_2

array([2, 3, 4, 5])

In [9]:
arr_2.shape

(4,)

In [10]:
#Get the data type of the array
type(arr_2)

numpy.ndarray

### Sorting an array

In [11]:
arr_7 = np.array([5,6,3,2,9])
arr_7

array([5, 6, 3, 2, 9])

In [12]:
np.sort(arr_7)

array([2, 3, 5, 6, 9])

In [13]:
np.sort(arr_7)[::-1]

array([9, 6, 5, 3, 2])

In [14]:
arr_8= np.array([[3,6,5],[4,6,7],[1,6,8]])
arr_8

array([[3, 6, 5],
       [4, 6, 7],
       [1, 6, 8]])

In [15]:
#sorting by columns
np.sort(arr_8,axis=1)

array([[3, 5, 6],
       [4, 6, 7],
       [1, 6, 8]])

In [16]:
#sorting by row
np.sort(arr_8,axis=0)

array([[1, 6, 5],
       [3, 6, 7],
       [4, 6, 8]])

### Creating Matrix Using Numpy

In [17]:
mat_1 = np.array([[1,2,3],[4,5,6]]) 

In [18]:
mat_1

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
mat_1.ndim

2

In [20]:
mat_1.shape

(2, 3)

#### Creating a matrix from list of list

In [21]:
lst_2 = [[2,3,4,5],[6,3,2,5], [3,4,7,5]]
lst_2

[[2, 3, 4, 5], [6, 3, 2, 5], [3, 4, 7, 5]]

In [22]:
mat_2 = np.array(lst_2)

In [23]:
mat_2

array([[2, 3, 4, 5],
       [6, 3, 2, 5],
       [3, 4, 7, 5]])

In [24]:
mat_2.ndim

2

In [25]:
mat_2.shape

(3, 4)

In [26]:
# creating a two by two matrix using np.matrix
matrix_1 =np.matrix([[1,2],[3,4]])
matrix_1

matrix([[1, 2],
        [3, 4]])

### Mathematical Operations with Arrays

In [97]:
a = np.array([[2,4], [6,8]])
b = np.array([[1,7],[2,4]])

In [98]:
a

array([[2, 4],
       [6, 8]])

In [99]:
b

array([[1, 7],
       [2, 4]])

In [100]:
#addition
a+b

array([[ 3, 11],
       [ 8, 12]])

In [101]:
#subtraction
a-b

array([[ 1, -3],
       [ 4,  4]])

In [102]:
#multiplcation
a*b

array([[ 2, 28],
       [12, 32]])

In [103]:
b*a

array([[ 2, 28],
       [12, 32]])

In [105]:
# Division
a/b

array([[2.        , 0.57142857],
       [3.        , 2.        ]])

### Broadcasting

In [112]:
d = 5
arr_a = np.array([[5,6],[4,2]])
arr_b = np.array([2,3])

In [113]:
d

5

In [114]:
arr_a

array([[5, 6],
       [4, 2]])

In [115]:
arr_b

array([2, 3])

In [116]:
#scalar with array
d * arr_a

array([[25, 30],
       [20, 10]])

In [117]:
d+ arr_a

array([[10, 11],
       [ 9,  7]])

In [118]:
# adding arrays with different shapes
arr_a +arr_b

array([[7, 9],
       [6, 5]])

In [119]:
arr_a *arr_b

array([[10, 18],
       [ 8,  6]])

In [120]:
arr_b*arr_a

array([[10, 18],
       [ 8,  6]])

### Numpy Indexing and Selection

Numpy indexing is similar to indexing in list data structure.

For a 1D array, elementss are accessed using their integer indicies

In [27]:

arr_3 = np.arange(5,40,5)
arr_3

array([ 5, 10, 15, 20, 25, 30, 35])

In [28]:
# get the first element of arr_3
arr_3[0]

5

In [29]:
# get the third element of arr_3
arr_3[2]

15

In [30]:
# get the last element of arr_3
arr_3[-1]

35

In a 2D array, a pair of indicies separated by a conna to access individual elements.


In [31]:
array_4 = np.array([[2,5,6],[3,4,5]])

In [32]:
array_4

array([[2, 5, 6],
       [3, 4, 5]])

In [33]:
#Selecting the element in the first row and third column
array_4[0,2]

6

In [34]:
#Selecting the element in the second row and second column
array_4[1,1]

4

### Slicing Arrays

In [35]:
arr_3

array([ 5, 10, 15, 20, 25, 30, 35])

In [36]:
#The first three elements of arr_3
arr_3[:3]

array([ 5, 10, 15])

In [37]:
arr_3[1:5:2]

array([10, 20])

In [38]:
arr_3[3:6]

array([20, 25, 30])

In [39]:
mat_A = np.array(([3,6,9],[12,15,18],[21,24,27]))

In [40]:
mat_A

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [41]:
#Getting all elements in the second row
mat_A[1,:]

array([12, 15, 18])

In [42]:
#Getting all elements in the second column
mat_A[:,1]

array([ 6, 15, 24])

In [43]:
mat_A[2,1]

24

In [44]:
#Updating an element
mat_A[2,1] = 0

In [45]:
mat_A

array([[ 3,  6,  9],
       [12, 15, 18],
       [21,  0, 27]])

In [46]:
np.delete(mat_A, 0, axis =1)

array([[ 6,  9],
       [15, 18],
       [ 0, 27]])

In [47]:
mat_A

array([[ 3,  6,  9],
       [12, 15, 18],
       [21,  0, 27]])

In [48]:
np.delete(mat_A, 2, axis =0)

array([[ 3,  6,  9],
       [12, 15, 18]])

### Boolean Indexing
Selecting elements from an array that meet a certain condition.

The boolean condition is an expression that returns a true or false value for each element in an array.

In [49]:
array_5 = np.array([4,3,2,8])

In [50]:
#Selecting elements of array_5 greater than 3
array_5[array_5>3]

array([4, 8])

In [51]:
#Selecting elements of array_5 that is evenly divided by 2
array_5[array_5%2==0]

array([4, 2, 8])

In [52]:
#Selecting elements of array_5 less than 3

array_5[array_5<3]

array([2])

### Numpy Built in Functions

**size**

It is used to return the number of elements in a numpy array

In [53]:
arr_6 = np.array([[1,2], [3,4],[5,6]])
arr_6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
np.size(arr_6)

6

#### reshape

It is used to change the shape of an array without changing its data

In [55]:
arr_4 = np.arange(1,11)
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr_4.shape

(10,)

In [57]:
#Reshaping arr_4 to a 2x5 matrix
arr_4.reshape((2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
#Reshaping arr_4 to a 5X2 matrix
arr_4.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [59]:
arr_5 = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])
arr_5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
arr_5.reshape((2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

#### arange

It is a function that provdies a  1D array of evenly spaced values within a specific range.

The value of the stop is exclusive

The deafult step size between values is 1.

It has the following syntax:

`np.arange(stop)`

`np.arange(start,stop )`

`np.arange(start,stop,step)`


In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
np.arange(2,51,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

**linspace**

It is used to create a 1D array of evenly spaced values within a specified interval, with a specificed number of elements.

In [64]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [65]:
np.linspace(0,50,10, endpoint=False)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [66]:
np.linspace(20,30,10)

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

#### zeros

Generate an array of specific shape with values of zeros

In [67]:
z1 =np.zeros(2)
z1

array([0., 0.])

In [68]:
z1.ndim

1

In [69]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### ones

Generate an array of specific shape with values of ones

In [70]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [71]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**full**

Generate an array of specific shape with all elements initialized to a specific value.

In [72]:
np.full(5,3)

array([3, 3, 3, 3, 3])

In [73]:
np.full((4,5),2.0)

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

**eye**

Create identity matrix of a 2D array with ones on the diagonal and zeros elsewhere

In [74]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [75]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**diag**

It is used to create a 2D array with specific diagonal values and zeros elsewhere.

In [76]:
np.diag([3,6,9])

array([[3, 0, 0],
       [0, 6, 0],
       [0, 0, 9]])

In [77]:
np.diag([1,1,1,1])

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Universal Function

In [78]:
arr_9 = np.array([3,4,5,3,2,4,3,4,3])

In [79]:
np.sum(arr_9)

31

In [80]:
np.min(arr_9)

2

In [81]:
np.max(arr_9)

5

In [82]:
np.mean(arr_9)

3.4444444444444446

In [83]:
np.median(arr_9)

3.0

In [84]:
np.sqrt(arr_9) 

array([1.73205081, 2.        , 2.23606798, 1.73205081, 1.41421356,
       2.        , 1.73205081, 2.        , 1.73205081])

In [85]:
arr_10 = np.array([[3,4,5,3,2,4,3,4,3],[2,9,5,3,2,8,3,4,8]])
arr_10

array([[3, 4, 5, 3, 2, 4, 3, 4, 3],
       [2, 9, 5, 3, 2, 8, 3, 4, 8]])

In [86]:
arr_10.shape

(2, 9)

In [87]:
np.sum(arr_10,axis=0)

array([ 5, 13, 10,  6,  4, 12,  6,  8, 11])

In [88]:
np.sum(arr_10,axis=1)

array([31, 44])