In [1]:
#Numerical Python - Numpy

In [3]:
import numpy as np

In [5]:
lst_1 = [1,2,3,4,5]

In [8]:
type(lst_1)

list

### Numpy Array

In [6]:
arr_1 = np.array([1,2,3,4,5])

In [7]:
arr_1

array([1, 2, 3, 4, 5])

In [9]:
type(arr_1)

numpy.ndarray

In [10]:
#Number of dimension
arr_1.ndim

1

In [11]:
#Shape of the array
arr_1.shape

(5,)

In [15]:
#Data type
arr_1.dtype

dtype('int32')

In [16]:
lst_1

[1, 2, 3, 4, 5]

In [17]:
np.array(lst_1)

array([1, 2, 3, 4, 5])

### Matrix

In [18]:
mat_1 = np.array([[1,2],[3,4]])

In [19]:
mat_1

array([[1, 2],
       [3, 4]])

In [20]:
mat_1.shape

(2, 2)

In [22]:
mat_1.ndim

2

In [23]:
lst_2 =[[1,2,3],[4,5,6]]

In [24]:
lst_2

[[1, 2, 3], [4, 5, 6]]

In [25]:
mat_2 = np.array(lst_2)

In [26]:
mat_2

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
mat_2.shape

(2, 3)

In [29]:
mat_2.ndim

2

In [30]:
mat_3 = np.array([[1,2],[3,4],[5,6]])

In [31]:
mat_3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
mat_3.ndim

2

In [34]:
mat_3.shape

(3, 2)

### Mathematical Operations

In [35]:
mat_a = np.array([[2,4],[6,8]])
mat_b = np.array([[1,7],[2,4]])

In [36]:
mat_a + mat_b

array([[ 3, 11],
       [ 8, 12]])

In [37]:
mat_a - mat_b

array([[ 1, -3],
       [ 4,  4]])

In [38]:
mat_a * mat_b

array([[ 2, 28],
       [12, 32]])

In [39]:
mat_b * mat_a

array([[ 2, 28],
       [12, 32]])

In [41]:
mat_b / mat_a

array([[0.5       , 1.75      ],
       [0.33333333, 0.5       ]])

In [42]:
lst_1 = [1,2,3,4,5]

In [43]:
[num+2 for num in lst_1]

[3, 4, 5, 6, 7]

In [44]:
arr_3 = np.array(lst_1)

In [45]:
arr_3

array([1, 2, 3, 4, 5])

In [46]:
arr_3+2

array([3, 4, 5, 6, 7])

In [47]:
arr_3*5

array([ 5, 10, 15, 20, 25])

In [48]:
list(range(4,12,1))

[4, 5, 6, 7, 8, 9, 10, 11]

In [49]:
arr_6 =np.arange(4,12,1)
arr_6

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
arr_6[0]

4

In [51]:
arr_6[2]

6

In [52]:
arr_6[-1]

11

In [53]:
mat_4 = np.array([[2,5,6], [3,4,5]])

In [54]:
mat_4

array([[2, 5, 6],
       [3, 4, 5]])

In [56]:
mat_4[0,2]

6

In [57]:
mat_4[1,1]

4

In [61]:
mat_4[1,1]

4

In [62]:
arr_6

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
arr_6[:3]

array([4, 5, 6])

In [65]:
arr_6[0:3]

array([4, 5, 6])

In [66]:
mat_4

array([[2, 5, 6],
       [3, 4, 5]])

In [67]:
mat_4[1:,1:]

array([[4, 5]])

In [71]:
mat_4[0:,1:]

array([[5, 6],
       [4, 5]])

In [72]:
mat_4[:,1:]

array([[5, 6],
       [4, 5]])

In [73]:
mat_4[0:2,1:]

array([[5, 6],
       [4, 5]])

In [74]:
mat_4

array([[2, 5, 6],
       [3, 4, 5]])

In [75]:
mat_4[0,1] = 8

In [76]:
mat_4

array([[2, 8, 6],
       [3, 4, 5]])

In [77]:
#axis 1= column
np.delete(mat_4,0, axis=1)

array([[8, 6],
       [4, 5]])

In [79]:
#axis 0 = row

np.delete(mat_4,1, axis=0)

array([[2, 8, 6]])

In [80]:
arr_7 = np.array([3,4,5,6,2,7,8,9,5])

In [81]:
arr_7

array([3, 4, 5, 6, 2, 7, 8, 9, 5])

In [82]:
#Greater than 7
arr_7[arr_7 > 7]

array([8, 9])

In [83]:
#less than 7
arr_7[arr_7 < 7]

array([3, 4, 5, 6, 2, 5])

In [84]:
arr_7

array([3, 4, 5, 6, 2, 7, 8, 9, 5])

In [85]:
arr_7[arr_7%2==0]

array([4, 6, 2, 8])

In [86]:
np.sort(arr_7)

array([2, 3, 4, 5, 5, 6, 7, 8, 9])

In [87]:
arr_7

array([3, 4, 5, 6, 2, 7, 8, 9, 5])

In [88]:
np.size(arr_7)

9

In [89]:
arr_8 =np.array([3,4,4,5,6,4])

In [90]:
arr_8

array([3, 4, 4, 5, 6, 4])

In [91]:
arr_8.reshape((2,3))

array([[3, 4, 4],
       [5, 6, 4]])

In [92]:
arr_8.reshape((3,2))

array([[3, 4],
       [4, 5],
       [6, 4]])

In [94]:
# arr_8.reshape((3,3))

In [96]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [97]:
np.zeros(4)

array([0., 0., 0., 0.])

In [98]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
np.ones(2)

array([1., 1.])

In [101]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [103]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [104]:
np.diag([3,6,9])

array([[3, 0, 0],
       [0, 6, 0],
       [0, 0, 9]])

In [105]:
arr_7

array([3, 4, 5, 6, 2, 7, 8, 9, 5])

In [106]:
np.sum(arr_7)

49

In [107]:
np.min(arr_7)

2

In [108]:
np.max(arr_7)

9

In [109]:
np.median(arr_7)

5.0

In [110]:
np.sqrt(arr_7)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 1.41421356,
       2.64575131, 2.82842712, 3.        , 2.23606798])